apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: online-boutique-dev
  namespace: argocd
spec:
  description: Project for online-boutique

  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'

  sourceRepos:
    - 'https://gitlab.com/thesis7100538/online_boutique/*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'