image:
  repository: 418295694191.dkr.ecr.ap-southeast-1.amazonaws.com/adservice
  tag: latest
imagePullSecrets:
- name: ecr-credentials
deployments:
- name: adservice
  replicasCount: 1
  prometheusEnabled: false
  service:
    name: adservice
    HTTPPort: 9555
    healthType: grpc
    health:
      #livenessCMD: ["/bin/grpc_health_probe", "-addr=:9555"]
      #readinessCMD: ["/bin/grpc_health_probe", "-addr=:9555"]
      livenessPort: 9555
      readinessPort: 9555
      initialDelaySeconds: 100
      periodSeconds: 10
      failureThreshold: 5
      timeoutSeconds: 3
env:
  PORT: 9555
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "100Mi"
infisical:
  enabled: false
