image:
  repository: 418295694191.dkr.ecr.ap-southeast-1.amazonaws.com/frontend
  tag: latest
imagePullSecrets:
- name: ecr-credentials
deployments:
- name: frontend
  replicasCount: 1
  prometheusEnabled: false
  service:
    name: frontend
    HTTPPort: 80
    health:
      livenessPort: 80
      readinessPort: 80
      initialDelaySeconds: 100
      periodSeconds: 10
      failureThreshold: 5
      timeoutSeconds: 3
port: 80
env:
  PORT: 80
  DISABLE_PROFILER: 0
  ENABLE_TRACING: 0
  AD_SERVICE_ADDR: adservice:80
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:80
  CURRENCY_SERVICE_ADDR: currencyservice:80
  CART_SERVICE_ADDR: cartservice:80
  RECOMMENDATION_SERVICE_ADDR: recommendationservice:80
  SHIPPING_SERVICE_ADDR: shippingservice:80
  CHECKOUT_SERVICE_ADDR: checkoutservice:80
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "100m"
    memory: "50Mi"
infisical:
  enabled: false
