image:
  repository: 418295694191.dkr.ecr.ap-southeast-1.amazonaws.com/productcatalogservice
  tag: latest
imagePullSecrets:
- name: ecr-credentials
deployments:
- name: productcatalogservice
  replicasCount: 1
  prometheusEnabled: false
  service:
    name: productcatalogservice
    HTTPPort: 3550
    health:
      livenessPort: 3550
      readinessPort: 3550
      initialDelaySeconds: 100
      periodSeconds: 10
      failureThreshold: 5
      timeoutSeconds: 3
env:
  PORT: 3550
port: 3550
resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "100m"
    memory: "100Mi"
infisical:
  enabled: false
