image:
  repository: 418295694191.dkr.ecr.ap-southeast-1.amazonaws.com/shippingservice
  tag: latest
imagePullSecrets:
- name: ecr-credentials
deployments:
- name: shippingservice
  replicasCount: 1
  prometheusEnabled: false
  service:
    name: shippingservice
    HTTPPort: 50051
    health:
      livenessPort: 50051
      readinessPort: 50051
      initialDelaySeconds: 100
      periodSeconds: 10
      failureThreshold: 5
      timeoutSeconds: 3
env:
  PORT: 50051
  PRODUCT_CATALOG_SERVICE_ADDR: productcatalogservice:3550
resources:
  requests:
    cpu: "100m"
    memory: "50Mi"
  limits:
    cpu: "100m"
    memory: "50Mi"
infisical:
  enabled: false
