repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: sonarqube
    namespace: sonarqube
    chart: bitnami/sonarqube
    version: 8.1.17
    values:
      - values.yaml                 
      - global:
          security:
            allowInsecureImages: true   
          postgresql:                
            auth:
              username: sonar
              database: sonarqube
