repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: promtail
    namespace: monitoring
    chart: grafana/promtail
    version: 6.17.0
    values:
      - values.yaml