daemonset:
  enabled: true
config:
  clients:
  - url: http://loki-gateway/loki/api/v1/push
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: CriticalAddonsOnly
    operator: Equal
    value: "true"
    effect: NoSchedule