repositories:
  - name: gitlab
    url: https://charts.gitlab.io

releases:
  - name: gitlab-runner
    namespace: gitlab-runner
    chart: gitlab/gitlab-runner
    version: 0.80.1
    values:
      - values.yaml