apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: spot-nodeclass
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-0ebf74f8ba7318d44
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 30Gi
        volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: "Karpenter-tool-cluster-dev-20250916095059973200000016"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "tool-cluster-dev"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "tool-cluster-dev"
  tags:
    karpenter.sh/discovery: "tool-cluster-dev"

---

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: spot-pool
spec:
  disruption:
    budgets:
    - nodes: "1"
    consolidateAfter: 2m
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        type: karpenter
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: spot-nodeclass
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["spot", "on-demand"]
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["t3.medium"]