apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: online-boutique-dev
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jqPathExpressions:
      - .spec.source.helm.parameters
  generators:
    - list:
        elements:
          - name: adservice
          - name: cartservice
          - name: checkoutservice
          - name: currencyservice
          - name: emailservice
          - name: frontend
          - name: paymentservice
          - name: productcatalogservice
          - name: recommendationservice
          - name: shippingservice
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/app.allow-tags: regexp:^[0-9a-f]{8}-dev$
        argocd-image-updater.argoproj.io/app.ignore-tags: latest,regexp:^latest.*$,regexp:^[0-9a-f]{8}-(prod|stage)
        argocd-image-updater.argoproj.io/app.update-strategy: newest-build
        argocd-image-updater.argoproj.io/app.helm.image-name: image.name
        argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
        argocd-image-updater.argoproj.io/image-list: app=043902793725.dkr.ecr.ap-southeast-1.amazonaws.com/{{name}}
        argocd-image-updater.argoproj.io/app.pull-secret: pullsecret:argocd/ecr-credentials
    spec:
      project: online-boutique-dev
      source:
        repoURL: https://gitlab.com/thesis7100538/online_boutique/helm-values.git
        targetRevision: main
        path: helm-general
        helm:
          valueFiles:
            - ../{{name}}-values.yaml
      destination:
        # name: "shoeshop-dev"
        name: "in-cluster"
        namespace: online-boutique
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true