repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: redis
    namespace: redis
    chart: bitnami/redis
    version: 22.0.7
    values:
      - values.yaml