repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: grafana
    namespace: monitoring
    chart: bitnami/grafana
    version: 12.1.8
    values:
      - values.yaml