affinity: {}
authScripts:
  enabled: false
  scripts: {}
config:
  applicationsAPIKind: ""
  argocd:
    grpcWeb: true
    insecure: false
    plaintext: false
    serverAddress: ""
    token: ""
  disableKubeEvents: false
  gitCommitMail: ""
  gitCommitTemplate: ""
  gitCommitUser: ""
  logLevel: trace
  registries:
  - api_url: https://043902793725.dkr.ecr.ap-southeast-1.amazonaws.com
    credentials: pullsecret:argocd/ecr-credentials
    defaultns: library
    name: Docker Hub
    ping: true
extraArgs:
- --registries-conf-path
- /app/config/registries.conf
image:
  pullPolicy: Always
  repository: quay.io/argoprojlabs/argocd-image-updater
  tag: v0.13.1
rbac:
  enabled: true
replicaCount: 1
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
serviceAccount:
  create: true
updateStrategy:
  type: Recreate